### ISSUE TITLE
Optimisation de la pioche de diodes

### ISSUE THREAD

**Issue by Shivien** [Khaali-dev/omega#5]
Dans le fichier "module\common\roll.js" fonction "piocher" ligne 145.

Le fait de repiocher une diode en boucle jusqu'à en obtenir une que l'on n'a pas déjà piocher n'est pas optimum. Il vaudrait mieux simuler le contenu d'un sac et piocher en retirant la valeur.

- Créer une table contenant les valeurs 1 à 30.
- Mélanger la table.
- Lire et retirer une valeur de la table plusieurs fois.

Voici le code :
``` JS
const bag = Array.from(Array(30).keys()).map(i => i + 1); // Sac contient 1..30.

// Mélanger le sac (algorithme Fisher-Yates).
for (let i = bag.length - 1; i > 0; i--) {
  const r = Math.floor(Math.random() * (i + 1)); // Nombre aléatoire entre 0 et i.
  const temp = bag[i];
  bag[i] = bag[r];
  bag[r] = temp;
}

for (let i = 0; i < this.data.nbDiodes; i++) {
  const value = bag.pop(); // Lire et retirer une diode.
  const color = color(value); // Récupérer la couleur à partir de la valeur pioché.
  this.data.diodesResult.push({ value, color });
  this.data.diodesSorties.push(value);
  this.data.diodesParCouleur[color] += 1;
}
```

Avec la fonction pour récupérer la couleur (créé à partir du code de la fonction "piocherDiode") :
``` JS
color(value) {
  if (value < 4) return "noire";
  else if (value > 27) return "rouge";
  else if (value > 21) return "verte";
  else if (value > 15) return "bleue";
  return "blanche";
}
```

Cordialement.

**Comment by Khaali-dev** [comment]
Merci! je regarderai ca dès que j'ai le temps.

**Comment by Khaali-dev** [comment]
Intégré dans 2.1.0
